# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow - untitledriCJBK.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from cpuinfo import get_cpu_info
from gpiozero import CPUTemperature

import res_rc
import GPUtil
import psutil
import datetime
import time
import matplotlib

gpus = GPUtil.getGPUs()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(2028, 595)
        MainWindow.setFocusPolicy(Qt.StrongFocus)
        MainWindow.setStyleSheet(u"background-color: rgb(13, 56, 113);\n"
                                 "color: rgb(255, 255, 255);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btn = QPushButton(self.centralwidget)
        self.btn.setObjectName(u"btn")
        self.btn.setGeometry(QRect(590, 40, 51, 51))
        self.btn.setCursor(QCursor(Qt.ArrowCursor))
        self.btn.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.btn.setToolTipDuration(-1)
        self.btn.setStyleSheet(u"background-color: rgb(255, 204, 0);")
        icon = QIcon()
        icon.addFile(u":/newPrefix/resources/home.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.btn.setIcon(icon)
        self.btn.setIconSize(QSize(40, 40))
        self.btn1 = QPushButton(self.centralwidget)
        self.btn1.setObjectName(u"btn1")
        self.btn1.setGeometry(QRect(490, 40, 51, 51))
        self.btn1.setCursor(QCursor(Qt.ArrowCursor))
        self.btn1.setFocusPolicy(Qt.StrongFocus)
        self.btn1.setStyleSheet(u"background-color: rgb(255, 183, 0);")
        self.btn1.setIcon(icon)
        self.btn1.setIconSize(QSize(40, 40))
        self.btn2 = QPushButton(self.centralwidget)
        self.btn2.setObjectName(u"btn2")
        self.btn2.setGeometry(QRect(390, 40, 51, 51))
        self.btn2.setStyleSheet(u"background-color: rgb(255, 136, 0);")
        self.btn2.setIcon(icon)
        self.btn2.setIconSize(QSize(40, 40))
        self.btn3 = QPushButton(self.centralwidget)
        self.btn3.setObjectName(u"btn3")
        self.btn3.setGeometry(QRect(290, 40, 51, 51))
        self.btn3.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.btn3.setIcon(icon)
        self.btn3.setIconSize(QSize(40, 40))
        self.btn4 = QPushButton(self.centralwidget)
        self.btn4.setObjectName(u"btn4")
        self.btn4.setGeometry(QRect(190, 40, 51, 51))
        self.btn4.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
                                "border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.33 rgba(0, 0, 0, 255), stop:0.34 rgba(255, 30, 30, 255), stop:0.66 rgba(255, 0, 0, 255), stop:0.67 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 0, 255));")
        self.btn4.setIcon(icon)
        self.btn4.setIconSize(QSize(40, 40))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(140, 120, 541, 351))
        self.frame.setStyleSheet(u"background-color: rgb(64, 131, 255);\n"
                                 "background-color: rgb(46, 101, 203);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.plainTextEdit = QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(70, 40, 391, 251))
        self.plainTextEdit.setStyleSheet(u"color: rgb(255, 255, 255);\n"
                                         "font: 12pt \"Times New Roman\";")
        self.plainTextEdit.setFrameShape(QFrame.NoFrame)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(750, 120, 541, 351))
        self.frame_2.setStyleSheet(u"background-color: rgb(64, 131, 255);\n"
                                   "background-color: rgb(46, 101, 203);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.progressBar = QProgressBar(self.frame_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(170, 120, 118, 23))
        self.progressBar.setValue(psutil.cpu_percent(interval=1))
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 10, 49, 16))
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 50, 49, 16))
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 70, 49, 16))
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 50, 131, 16))
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 70, 131, 16))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 120, 61, 16))
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(80, 170, 61, 16))
        self.progressBar_2 = QProgressBar(self.frame_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(170, 170, 118, 23))
        self.progressBar_2.setValue(gpus[0].load * 100)
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(80, 230, 81, 16))
        self.label_14 = QLabel(self.frame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 270, 81, 16))
        self.lcdNumber = QLCDNumber(self.frame_2)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(170, 230, 64, 23))
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setProperty("intValue", 10)
        self.lcdNumber_2 = QLCDNumber(self.frame_2)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(170, 270, 64, 23))
        self.lcdNumber_2.setLineWidth(1)
        self.lcdNumber_2.setMidLineWidth(0)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setProperty("intValue", gpus[0].temperature)
        self.label_15 = QLabel(self.frame_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(350, 40, 121, 20))
        self.label_55 = QLabel(self.frame_2)
        self.label_55.setObjectName(u"label_15")
        self.label_55.setGeometry(QRect(350, 70, 121, 20))
        self.label_21 = QLabel(self.frame_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(350, 210, 101, 16))
        self.label_22 = QLabel(self.frame_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(350, 230, 91, 16))
        self.label_22.setStyleSheet(u"text-align: center;")
        self.label_23 = QLabel(self.frame_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(350, 270, 101, 16))
        self.label_24 = QLabel(self.frame_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(350, 250, 111, 16))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 90, 49, 16))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 90, 49, 16))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(390, 90, 49, 16))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(490, 90, 49, 16))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(590, 90, 49, 16))
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(1390, 120, 541, 351))
        self.frame_3.setStyleSheet(u"background-color: rgb(64, 131, 255);\n"
                                   "background-color: rgb(46, 101, 203);")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 10, 71, 16))
        self.label_17 = QLabel(self.frame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(70, 160, 171, 51))
        self.label_17.setStyleSheet(u"font: 22pt \"Segoe UI\";")
        self.label_18 = QLabel(self.frame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(140, 140, 49, 16))
        self.label_19 = QLabel(self.frame_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(380, 140, 49, 16))
        self.label_20 = QLabel(self.frame_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(320, 170, 151, 31))
        self.label_20.setStyleSheet(u"font: 24pt \"Segoe UI\";")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn.setText("")
        self.btn1.setText("")
        self.btn2.setText("")
        self.btn3.setText("")
        self.btn4.setText("")
        self.plainTextEdit.setPlainText(QCoreApplication.translate("MainWindow", u"		About app:\n"
                                                                                 "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                                                                   None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"PC info:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"CPU:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"GPU:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", str(get_cpu_info()['brand_raw']), None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", gpus[0].name, None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"CPU Load:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"GPU Load:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"CPU Temp* (\u00b0C):", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"GPU Temp (\u00b0C):", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"GPU tot. memory: ", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", str(gpus[0].memoryTotal) + " Mb", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", str(gpus[0].memoryUsed) + " Mb", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"GPU used memory:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Virtual memory usage (%)", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", str(dict(psutil.virtual_memory()._asdict())['total']), None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"  Home", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"     PC", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"   Time", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"  Games", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"  Statistic", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Time & Date", None))
        self.label_17.setText(
            QCoreApplication.translate("MainWindow", str(datetime.date.today()).replace('-', '.'), None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Date", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", str(time.strftime('%X')), None))
    # retranslateUi


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
